const state={section:'chat',messages:[]};
const nav=[['chat','Chat'],['think','Think'],['codex','Codex'],['recent','Recent'],['projects','Projects'],['memory','Memory'],['library','Library'],['maps','Maps'],['images','Images'],['scheduled','Scheduled'],['plugins','Plugins'],['diagnostics','Diagnostics'],['settings','Settings']];
const $=s=>document.querySelector(s);const esc=s=>String(s).replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\\':'&#92;','"':'&quot;'}[c]));
async function api(path,opt={}){const r=await fetch(path,opt);const j=await r.json().catch(()=>({error:'Invalid response'}));if(!r.ok)throw new Error(j.error||`HTTP ${r.status}`);return j}
function renderNav(){ $('#nav').innerHTML=nav.map(([id,t])=>`<button class="${state.section===id?'active':''}" data-id="${id}">${t}</button>`).join('');document.querySelectorAll('#nav button').forEach(b=>b.onclick=()=>{state.section=b.dataset.id;render()}) }
async function render(){renderNav();const c=$('#content'),title=$('#title');title.textContent=nav.find(x=>x[0]===state.section)?.[1]||'CORE-AI';if(state.section==='chat'||state.section==='think'||state.section==='codex'){c.innerHTML=state.messages.map(m=>`<div class="msg ${m.role}">${esc(m.text)}</div>`).join('')||`<div class="card"><strong>${state.section==='chat'?'New Chat':state.section.toUpperCase()}</strong><div class="muted">Real backend state only. No sample conversation is generated.</div></div>`;return}try{if(state.section==='recent'){const j=await api('/conversations/recent');c.innerHTML=`<div class="card">${j.map(x=>`<div class="row"><span>${esc(x.title)}</span><span class="pill">${x.id.slice(0,8)}</span></div>`).join('')||'<span class="muted">No conversations yet.</span>'}</div>`;return}if(state.section==='projects'){const j=await api('/projects');c.innerHTML=`<div class="card">${j.map(x=>`<div class="row"><span>${esc(x.name)}</span><span class="muted">${esc(x.root)}</span></div>`).join('')||'<span class="muted">No projects yet.</span>'}</div>`;return}if(state.section==='memory'){const j=await api('/memory/search?q=');c.innerHTML=`<div class="card">${j.map(x=>`<div class="row"><span>${esc(x.content)}</span><span class="pill">${esc(x.scope)}</span></div>`).join('')||'<span class="muted">No memory entries.</span>'}</div>`;return}const map={library:'Library service is not enabled in this build.',maps:'Maps backend is UNAVAILABLE until a provider is configured.',images:'Image generation backend is UNAVAILABLE until a provider is configured.',scheduled:'Scheduler persistence exists; execution is not enabled.',plugins:'Plugin metadata surface exists; sandboxed execution is not enabled.',diagnostics:'Diagnostics: use core-ai status / core-ai capabilities.',settings:'Settings are persisted in the runtime config; advanced controls are not enabled yet.'};c.innerHTML=`<div class="card"><strong>${esc(state.section)}</strong><div class="muted">${esc(map[state.section]||'No data')}</div></div>`}catch(e){c.innerHTML=`<div class="card"><strong>FAILED</strong><div class="muted">${esc(e.message)}</div></div>`}}
async function refresh(){try{const s=await api('/status');$('#status').textContent=`${s.ollama_reachable?'Ollama READY':'Ollama UNAVAILABLE'} · ${s.privacy_mode} · ${s.model}`;$('#model').innerHTML=`<option>${esc(s.model)}</option>`}catch(e){$('#status').textContent='Core OFFLINE · '+e.message}}
$('#newBtn').onclick=async()=>{try{await api('/conversations/new',{method:'POST'});state.messages=[];state.section='chat';await render()}catch(e){alert(e.message)}};
$('#resetBtn').onclick=async()=>{try{await api('/conversations/reset',{method:'POST'});state.messages=[];await render()}catch(e){alert(e.message)}};
$('#composer').onsubmit=async e=>{e.preventDefault();const input=$('#input'),text=input.value.trim();if(!text)return;const role='user';state.messages.push({role,text});await render();input.value='';try{const mode=$('#mode').value;const j=await api('/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({mode,prompt:text})});state.messages.push({role:'assistant',text:j.text||j.error||''});}catch(e){state.messages.push({role:'assistant',text:'ERROR: '+e.message})}await render()};
render();refresh();setInterval(refresh,5000);
