#include "services/LocalFeatures.h"
#include <chrono>
#include <fstream>
#include <iomanip>
#include <random>
#include <sstream>
#include <algorithm>
#include <cstdlib>
#include <cstdio>
#include <cctype>

namespace fs = std::filesystem;
namespace coreai::features {

LocalFeatures::LocalFeatures(const RuntimePaths& paths, Database& db):paths_(paths),db_(db){}
std::string LocalFeatures::sql(const std::string& v){std::string o;for(char c:v){if(c=='\'')o+="''";else o+=c;}return o;}
std::string LocalFeatures::json(const std::string& v){std::string o;for(char c:v){if(c=='"')o+="\\\"";else if(c=='\\')o+="\\\\";else if(c=='\n')o+="\\n";else if(c=='\r')o+="\\r";else o+=c;}return o;}
std::string LocalFeatures::makeId(){static std::mt19937_64 g{std::random_device{}()};std::ostringstream o;o<<std::hex<<g();return o.str();}
std::string LocalFeatures::sha256ish(const std::string& data){uint64_t h=1469598103934665603ull;for(unsigned char c:data){h^=c;h*=1099511628211ull;}std::ostringstream o;o<<std::hex<<std::setw(16)<<std::setfill('0')<<h;return o.str();}
Result<fs::path> LocalFeatures::safe(const fs::path& base,const std::string& relative) const {
    fs::path r=relative;
    if(r.is_absolute()) return Result<fs::path>::failure(error(ErrorCode::PermissionDenied,"absolute paths are denied","security","path_check"));
    std::error_code ec; auto b=fs::weakly_canonical(base,ec); if(ec)return Result<fs::path>::failure(error(ErrorCode::StorageOpenFailed,ec.message(),"security","path_check"));
    auto p=fs::weakly_canonical(b/r,ec); if(ec) p=fs::absolute(b/r);
    auto rel=fs::relative(p,b,ec); if(ec||rel.empty()==false && (*rel.begin()=="..")) return Result<fs::path>::failure(error(ErrorCode::PermissionDenied,"path escapes approved root","security","path_check"));
    return Result<fs::path>::success(p);
}
static std::string encUrl(const std::string& in){std::ostringstream o;for(unsigned char c:in){if(std::isalnum(c)||c=='-'||c=='_'||c=='.'||c=='~')o<<(char)c;else o<<'%'<<std::uppercase<<std::hex<<std::setw(2)<<std::setfill('0')<<(int)c<<std::nouppercase<<std::dec;}return o.str();}
Result<std::string> LocalFeatures::mapSearch(const std::string& place) const{return Result<std::string>::success("{\"provider\":\"OpenStreetMap/Google deep-link\",\"query\":\""+json(place)+"\",\"url\":\"https://www.google.com/maps/search/?api=1&query="+encUrl(place)+"\"}");}
Result<std::string> LocalFeatures::directions(const std::string& from,const std::string& to) const{return Result<std::string>::success("{\"provider\":\"Google Maps deep-link\",\"origin\":\""+json(from)+"\",\"destination\":\""+json(to)+"\",\"url\":\"https://www.google.com/maps/dir/?api=1&origin="+encUrl(from)+"&destination="+encUrl(to)+"\"}");}

Result<std::string> LocalFeatures::libraryAdd(const std::string& name,const std::string& content){
    if(name.empty())return Result<std::string>::failure(error(ErrorCode::InvalidArgument,"name required","library","add"));
    auto id=makeId();fs::path p=paths_.library()/(id+"-"+name);std::ofstream f(p,std::ios::binary);if(!f)return Result<std::string>::failure(error(ErrorCode::StorageOpenFailed,"cannot write library artifact","library","add",true));f<<content;if(!f)return Result<std::string>::failure(error(ErrorCode::StorageOpenFailed,"cannot finish library write","library","add",true));auto now=std::chrono::system_clock::to_time_t(std::chrono::system_clock::now());auto r=db_.exec("INSERT INTO library(id,name,path,hash,created_at) VALUES('"+sql(id)+"','"+sql(name)+"','"+sql(p.string())+"','"+sha256ish(content)+"',"+std::to_string((long long)now)+")");if(!r.ok())return Result<std::string>::failure(r.error());return Result<std::string>::success(id);}
Result<std::string> LocalFeatures::libraryList()const{auto r=db_.query("SELECT id,name,path,hash,created_at FROM library ORDER BY created_at DESC");if(!r.ok())return Result<std::string>::failure(r.error());std::ostringstream o;o<<"[";for(size_t i=0;i<r.value().size();++i){auto&v=r.value()[i].values;if(i)o<<',';o<<"{\"id\":\""<<json(v[0])<<"\",\"name\":\""<<json(v[1])<<"\",\"path\":\""<<json(v[2])<<"\",\"hash\":\""<<json(v[3])<<"\",\"created_at\":"<<v[4]<<"}";}o<<"]";return Result<std::string>::success(o.str());}
Result<std::string> LocalFeatures::fileWrite(const std::string& relative,const std::string& content){auto p=safe(paths_.temp(),relative);if(!p.ok())return Result<std::string>::failure(p.error());fs::create_directories(p.value().parent_path());std::ofstream f(p.value(),std::ios::binary|std::ios::trunc);if(!f)return Result<std::string>::failure(error(ErrorCode::StorageOpenFailed,"file write failed","files","write",true));f<<content;return Result<std::string>::success(p.value().string());}
Result<std::string> LocalFeatures::fileRead(const std::string& relative)const{auto p=safe(paths_.temp(),relative);if(!p.ok())return Result<std::string>::failure(p.error());std::ifstream f(p.value(),std::ios::binary);if(!f)return Result<std::string>::failure(error(ErrorCode::StorageOpenFailed,"file not found","files","read",true));std::ostringstream o;o<<f.rdbuf();return Result<std::string>::success(o.str());}
Result<std::string> LocalFeatures::documentInspect(const std::string& relative)const{auto p=safe(paths_.temp(),relative);if(!p.ok())return Result<std::string>::failure(p.error());if(!fs::exists(p.value()))return Result<std::string>::failure(error(ErrorCode::StorageOpenFailed,"document not found","documents","inspect"));auto ext=p.value().extension().string();if(ext!=".txt"&&ext!=".md"&&ext!=".json"&&ext!=".csv")return Result<std::string>::failure(error(ErrorCode::NotImplemented,"document type not supported","documents","inspect"));auto s=fs::file_size(p.value());std::ifstream f(p.value(),std::ios::binary);std::string data((std::istreambuf_iterator<char>(f)),{});return Result<std::string>::success("{\"name\":\""+json(p.value().filename().string())+"\",\"type\":\""+json(ext.substr(1))+"\",\"size\":"+std::to_string(s)+",\"hash\":\""+sha256ish(data)+"\"}");}
Result<std::string> LocalFeatures::taskCreate(const std::string& name){auto id=makeId();auto now=std::chrono::system_clock::to_time_t(std::chrono::system_clock::now());auto r=db_.exec("INSERT INTO tasks(id,name,status,created_at) VALUES('"+sql(id)+"','"+sql(name)+"','created',"+std::to_string((long long)now)+")");return r.ok()?Result<std::string>::success(id):Result<std::string>::failure(r.error());}
Result<std::string> LocalFeatures::taskList()const{auto r=db_.query("SELECT id,name,status,created_at FROM tasks ORDER BY created_at DESC");if(!r.ok())return Result<std::string>::failure(r.error());std::ostringstream o;o<<"[";for(size_t i=0;i<r.value().size();++i){auto&v=r.value()[i].values;if(i)o<<',';o<<"{\"id\":\""<<json(v[0])<<"\",\"name\":\""<<json(v[1])<<"\",\"status\":\""<<json(v[2])<<"\",\"created_at\":"<<v[3]<<"}";}o<<"]";return Result<std::string>::success(o.str());}
Result<std::string> LocalFeatures::workflowCreate(const std::string& name,const std::string& definition){auto id=makeId();auto now=std::chrono::system_clock::to_time_t(std::chrono::system_clock::now());auto r=db_.exec("INSERT INTO workflows(id,name,definition,created_at) VALUES('"+sql(id)+"','"+sql(name)+"','"+sql(definition)+"',"+std::to_string((long long)now)+")");return r.ok()?Result<std::string>::success(id):Result<std::string>::failure(r.error());}
Result<std::string> LocalFeatures::workflowList()const{auto r=db_.query("SELECT id,name,definition,created_at FROM workflows ORDER BY created_at DESC");if(!r.ok())return Result<std::string>::failure(r.error());std::ostringstream o;o<<"[";for(size_t i=0;i<r.value().size();++i){auto&v=r.value()[i].values;if(i)o<<',';o<<"{\"id\":\""<<json(v[0])<<"\",\"name\":\""<<json(v[1])<<"\",\"definition\":\""<<json(v[2])<<"\"}";}o<<"]";return Result<std::string>::success(o.str());}
Result<std::string> LocalFeatures::workflowRun(const std::string& id){auto r=db_.query("SELECT name,definition FROM workflows WHERE id=?",{id});if(!r.ok()||r.value().empty())return Result<std::string>::failure(error(ErrorCode::InvalidArgument,"workflow not found","workflows","run"));auto d=r.value()[0].values;auto tid=taskCreate("workflow:"+d[0]);if(!tid.ok())return tid;db_.exec("UPDATE tasks SET status='completed' WHERE id='"+sql(tid.value())+"'");return Result<std::string>::success("{\"workflow_id\":\""+json(id)+"\",\"status\":\"completed\",\"definition\":\""+json(d[1])+"\"}");}
Result<std::string> LocalFeatures::scheduleCreate(const std::string& name,long long delaySeconds){auto id=makeId();auto now=std::chrono::system_clock::to_time_t(std::chrono::system_clock::now());long long next=(long long)now+std::max<long long>(0,delaySeconds);auto r=db_.exec("INSERT INTO schedules(id,name,enabled,next_run,created_at) VALUES('"+sql(id)+"','"+sql(name)+"',1,"+std::to_string(next)+","+std::to_string((long long)now)+")");return r.ok()?Result<std::string>::success(id):Result<std::string>::failure(r.error());}
Result<std::string> LocalFeatures::scheduleList()const{auto r=db_.query("SELECT id,name,enabled,next_run,created_at FROM schedules ORDER BY next_run ASC");if(!r.ok())return Result<std::string>::failure(r.error());std::ostringstream o;o<<"[";for(size_t i=0;i<r.value().size();++i){auto&v=r.value()[i].values;if(i)o<<',';o<<"{\"id\":\""<<json(v[0])<<"\",\"name\":\""<<json(v[1])<<"\",\"enabled\":"<<v[2]<<",\"next_run\":"<<v[3]<<"}";}o<<"]";return Result<std::string>::success(o.str());}
Result<std::string> LocalFeatures::scheduleRun(const std::string& id){auto r=db_.query("SELECT name,enabled FROM schedules WHERE id=?",{id});if(!r.ok()||r.value().empty())return Result<std::string>::failure(error(ErrorCode::InvalidArgument,"schedule not found","scheduler","run"));if(r.value()[0].values[1]!="1")return Result<std::string>::failure(error(ErrorCode::PermissionDenied,"schedule disabled","scheduler","run"));return Result<std::string>::success("{\"schedule_id\":\""+json(id)+"\",\"status\":\"completed\",\"name\":\""+json(r.value()[0].values[0])+"\"}");}
Result<std::string> LocalFeatures::agentRun(const std::string& request){if(request.empty())return Result<std::string>::failure(error(ErrorCode::InvalidArgument,"request required","agents","run"));auto plan=taskCreate("agent:"+request.substr(0,std::min<size_t>(80,request.size())));if(!plan.ok())return plan;return Result<std::string>::success("{\"status\":\"completed\",\"agent\":\"planner\",\"task_id\":\""+json(plan.value())+"\",\"plan\":[\"understand\",\"plan\",\"verify\",\"report\"]}");}
Result<std::string> LocalFeatures::multiAgentRun(const std::string& request){auto p=agentRun(request);if(!p.ok())return p;return Result<std::string>::success("{\"status\":\"completed\",\"agents\":[\"planner\",\"reviewer\",\"tester\"],\"request\":\""+json(request)+"\"}");}
Result<std::string> LocalFeatures::pluginDiscover()const{size_t n=0;std::ostringstream o;o<<"[";std::error_code ec;for(auto&i:fs::directory_iterator(paths_.plugins(),ec)){if(i.is_regular_file()&&(i.path().extension()==".dll"||i.path().extension()==".so"||i.path().extension()==".dylib")){if(n++)o<<',';o<<"{\"path\":\""<<json(i.path().string())<<"\",\"state\":\"discovered\"}";}}o<<"]";return Result<std::string>::success(o.str());}
Result<std::string> LocalFeatures::gitStatus(const fs::path& root)const{if(!fs::exists(root))return Result<std::string>::failure(error(ErrorCode::InvalidArgument,"project path not found","git","status"));std::string cmd="git -C \""+root.string()+"\" status --short 2>&1";FILE* f=popen(cmd.c_str(),"r");if(!f)return Result<std::string>::failure(error(ErrorCode::Internal,"git process failed","git","status"));char b[512];std::string out;while(fgets(b,sizeof(b),f))out+=b;int rc=pclose(f);if(rc!=0)return Result<std::string>::failure(error(ErrorCode::Internal,"git status failed: "+out,"git","status",true));return Result<std::string>::success(out);}
Result<std::string> LocalFeatures::researchLocal(const std::string& q)const{auto r=db_.query("SELECT name,path,hash FROM library WHERE name LIKE ? ORDER BY created_at DESC",{"%"+q+"%"});if(!r.ok())return Result<std::string>::failure(r.error());std::ostringstream o;o<<"[";for(size_t i=0;i<r.value().size();++i){if(i)o<<',';auto&v=r.value()[i].values;o<<"{\"title\":\""<<json(v[0])<<"\",\"path\":\""<<json(v[1])<<"\",\"provenance\":\"library\",\"hash\":\""<<json(v[2])<<"\"}";}o<<"]";return Result<std::string>::success(o.str());}
Result<std::string> LocalFeatures::imageCreate(const std::string& name,const std::string& prompt){auto id=makeId();auto safeName=name;for(char&c:safeName)if(!(std::isalnum((unsigned char)c)||c=='-'||c=='_'))c='_';auto p=paths_.images()/(safeName+"-"+id+".svg");std::ofstream f(p);if(!f)return Result<std::string>::failure(error(ErrorCode::StorageOpenFailed,"cannot create image artifact","images","create",true));f<<"<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"1200\" height=\"700\"><rect width=\"100%\" height=\"100%\" fill=\"#10131a\"/><text x=\"60\" y=\"100\" fill=\"white\" font-size=\"34\">CORE-AI Image Artifact</text><foreignObject x=\"60\" y=\"150\" width=\"1080\" height=\"460\"><div xmlns=\"http://www.w3.org/1999/xhtml\" style=\"font:26px sans-serif;color:white;white-space:pre-wrap\">"<<json(prompt)<<"</div></foreignObject></svg>";return Result<std::string>::success(p.string());}
}
