#include "core/CoreApp.h"
#include "ai/OllamaProvider.h"
#include <cctype>
#include <cstdlib>
#include <filesystem>
#include <iomanip>
#include <sstream>
namespace core { static std::string enc(const std::string&s){std::ostringstream o;for(unsigned char c:s){if(std::isalnum(c)||c=='-'||c=='_'||c=='.'||c=='~')o<<(char)c;else o<<'%'<<std::uppercase<<std::hex<<std::setw(2)<<std::setfill('0')<<(int)c<<std::nouppercase<<std::dec;}return o.str();}
CoreApp::CoreApp():logger_("core.log"),memory_("memory.db.txt"),audit_("audit.log"),projects_("projects"){}
bool CoreApp::initialize(const std::string&r){root_=std::filesystem::absolute(r).string();std::filesystem::create_directories(std::filesystem::path(root_)/".core");config_.load((std::filesystem::path(root_)/"core.config").string());std::string m=config_.get("model",std::getenv("CORE_MODEL")?std::getenv("CORE_MODEL"):"llama3.2");models_.add(std::make_unique<ai::OllamaProvider>(m));tools_.add("web.search",[](const std::string&q){return "https://www.google.com/search?q="+enc(q);});tools_.add("maps.search",[](const std::string&q){return "https://www.google.com/maps/search/?api=1&query="+enc(q);});events_.emit("core.start",root_);logger_.info("CORE initialized at "+root_);return true;}
std::string CoreApp::chat(const std::string&p){auto*m=models_.select();if(!m)return "MODEL ERROR: no provider";std::ostringstream s;s<<"You are CORE AI, a personal AI system. Be accurate. Never claim an external action occurred unless verified.\nRelevant memory:\n";for(auto&m:memory_.search(p,5))s<<"- ["<<m.scope<<"] "<<m.text<<"\n";auto r=m->complete({s.str(),p});audit_.record("user","chat",r.ok?"success":"failed");return r.ok?r.text:"MODEL ERROR: "+r.error;}
std::string CoreApp::think(const std::string&p){return chat("Solve this carefully and give the useful conclusion. Do not expose private chain-of-thought. "+p);} std::string CoreApp::code(const std::string&p){return chat("Act as a coding assistant. Return practical code and key implementation notes without private chain-of-thought. "+p);} std::string CoreApp::agent(const std::string&p){std::string plan=agents_.planOnly(p);return chat("Use this deterministic plan as internal context, then complete the user's task. PLAN:\n"+plan+"\nTASK:\n"+p);}
std::string CoreApp::capabilities()const{return "native-core,chat,reasoning,coding,agent-planning,tool-registry,memory,projects,workflows,permissions,audit,verification,plugins,web-adapter,maps-adapter,replaceable-html-js-gui,c-api";}
std::string CoreApp::status()const{std::ostringstream o;auto ids=models_.ids();o<<"{\"version\":\"0.2.0\",\"model\":\""<<(ids.empty()?"":ids.front())<<"\",\"ollama\":"<<(models_.select()!=nullptr?"true":"false")<<",\"permissions\":{\"memory.write\":"<<(hasPermission("memory.write")?"true":"false")<<",\"file.write\":"<<(hasPermission("file.write")?"true":"false")<<",\"process.execute\":"<<(hasPermission("process.execute")?"true":"false")<<"}}";return o.str();}
std::string CoreApp::memorySearch(const std::string&q)const{std::ostringstream o;for(auto&m:memory_.search(q))o<<m.id<<" ["<<m.scope<<"] "<<m.text<<'\n';return o.str();} bool CoreApp::remember(const std::string&t,const std::string&s){if(!hasPermission("memory.write"))return false;return memory_.add(s,t);} std::string CoreApp::projectCreate(const std::string&n){if(!hasPermission("file.write"))return "DENIED: file.write";return projects_.create(n)?"PROJECT CREATED: "+n:"PROJECT ERROR";} std::string CoreApp::projectList()const{std::ostringstream o;for(auto&x:projects_.list())o<<x<<'\n';return o.str();} void CoreApp::grant(const std::string&p){permissions_.grant(p);audit_.record("user","permission.grant",p);} bool CoreApp::hasPermission(const std::string&p)const{return permissions_.allows(p);} std::string CoreApp::webSearchUrl(const std::string&q)const{return "https://www.google.com/search?q="+enc(q);} std::string CoreApp::mapUrl(const std::string&q)const{return "https://www.google.com/maps/search/?api=1&query="+enc(q);} std::string CoreApp::directionsUrl(const std::string&a,const std::string&b)const{return "https://www.google.com/maps/dir/?api=1&origin="+enc(a)+"&destination="+enc(b);} }
